xcopy /y "config.json" "Broker\config.json"
xcopy /y "config.json" "Buyer\config.json"
xcopy /y "config.json" "SFBroker\config.json"
xcopy /y "config.json" "SFBroker_DirectAccess\config.json"
xcopy /y "config.json" "SFBroker_DirectAccess\config.json"