xcopy /y "config.json" "Broker\config.json"
xcopy /y "config.json" "Client\config.json"
xcopy /y "config.json" "SFBroker\config.json"
xcopy /y "config.json" "SFBroker_DirectAccess\config.json"
xcopy /y "config.json" "SFBroker_DirectAccess\config.json"

xcopy /y "constants.js" "Broker\constants.js"
xcopy /y "constants.js" "Client\constants.js"
xcopy /y "constants.js" "SFBroker\constants.js"
xcopy /y "constants.js" "SFBroker_DirectAccess\constants.js"
xcopy /y "constants.js" "SFBroker_DirectAccess\constants.js"