version: '2'
services:

  mongodb-sfbroker:
      image: mongo:latest

  mongodb-broker:
     image: mongo:latest
     command: mongod --port 27018

  sf-broker:
    build: SFBroker/
    ports:
      - "18001:18001"
      - "18002:18002"
    depends_on:
      - mongodb-sfbroker

  broker:
    build: Broker/
    ports:
      - "18003:18003"
      - "18004:18004"
      - "34123:34123"
      - "63667:63667"
      - "49129:49129"
    depends_on:
      - mongodb-broker

  admin:
    build: Admin/
    ports:
      - "18009:18009"
    command: node server.js
    depends_on:
      - sf-broker

  frontend:
    build: Frontend/
    ports:
      - "4200:80"
    depends_on:
      - sf-broker