version: '2'
services:

  mongodb-sfbroker:
      image: mongo:latest

  mongodb-broker:
     image: mongo:latest
     command: mongod --port 27018

  sf-broker:
    build: SFBroker/
    ports:
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - mongodb-sfbroker

  broker:
    build: Broker/
    ports:
      - "8003:8003"
      - "8004:8004"
      - "34123:34123"
      - "63667:63667"
      - "49129:49129"
    depends_on:
      - mongodb-broker

  admin:
    build: Admin/
    ports:
      - "8009:8009"
    command: node server.js
    depends_on:
      - sf-broker

  frontend:
    build: Frontend/
    ports:
      - "4200:80"
    depends_on:
      - sf-broker