version: '2'
services:

  mongodb:
    build: Database/
    ports:
      - "27017:27017"

  sf-broker:
    build: SFBroker/
    ports:
      - "8001:8001"
    depends_on:
      - mongodb

  broker:
    build: Broker/
    ports:
      - "8003:8003"
      - "34123:34123"
      - "63667:63667"
      - "49129:49129"
    depends_on:
      - sf-broker

  frontend:
    build: Frontend/
    ports:
      - "4200:80"