version: '2'
services:

  mongodb-sfbroker:
      image: 'mongo:latest'

  mongodb-broker:
     image: 'mongo:latest'
     command: mongod --port 27018

  sf-broker:
    build: SFBroker/
    ports:
      - "8001:8001"
    depends_on:
      - mongodb-sfbroker

  broker:
    build: Broker/
    ports:
      - "8003:8003"
      - "34123:34123"
      - "63667:63667"
      - "49129:49129"
    depends_on:
      - mongodb-broker

  frontend:
    build: Frontend/
    ports:
      - "4200:80"
    depends_on:
      - sf-broker